# Generated by Django 2.0.5 on 2018-06-08 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_description', models.CharField(max_length=700)),
                ('activity_start_date', models.DateField()),
                ('activity_end_date', models.DateField()),
                ('activity_picture', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('MTR', 'Monetary'), ('RSR', 'Resources'), ('VLT', 'Volunteers')], default='MTR', editable=False, max_length=3)),
                ('donation_description', models.CharField(max_length=400)),
                ('activity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
            ],
        ),
    ]
