# Generated by Django 2.0.5 on 2018-06-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
