# Generated by Django 2.0.5 on 2018-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_auto_20180622_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('vida', 'Vida'), ('innovacion', 'Innovacion'), ('energia', 'Energia'), ('social', 'Social')], default='vida', editable=False, max_length=10),
        ),
    ]
