# Generated by Django 2.0.5 on 2018-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('vida', 'Vida'), ('innovacion', 'Innovacion'), ('energia', 'Energia'), ('social', 'Social')], default='vida', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('MTR', 'Monetary'), ('RSR', 'Resources'), ('VLT', 'Volunteers')], default='MTR', max_length=3),
        ),
    ]
