# Generated by Django 2.0.5 on 2018-06-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_donation_donation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
